language: python
python:
  - "2.7"
install:
- pip install pipenv
- pipenv install --dev
script:
- pylint createbillboardplaylist.py
- flake8 createbillboardplaylist.py
- python createbillboardplaylist_test.py
