on: [push, pull_request]

name: CI

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Set up pipenv
        run: pipenv install --dev
      - name: Lint with pylint
        run: pylint createbillboardplaylist.py
      - name: Lint with flake8
        run: flake8 createbillboardplaylist.py
      - name: Test with pytest
        run: python createbillboardplaylist_test.py
